
name: Awesome Lint

permissions:
  contents: read
  actions: read
  
on:
  push:
    branches: [main]
    paths:
      - 'README.md'
  pull_request:
    branches: [main]
    paths:
      - 'README.md'
jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint
        run: npx awesome-lint
      - name: Lint complete
        run: echo "✅ All markdown files passed awesome-lint"
